### ISSUE TITLE
请问一下输入emoji时，对于不能一次性输入的词汇怎么办。

### ISSUE THREAD

**Issue by EurekaChen** [GuoBinyong/wubixinshiji#2]
例如，我们输入“微笑”，可以得到emoji“🙂️”。因为“微笑”是一个可以一次性输入的词组。
但是“做运动女”这样的词组，对应的emoji有：“ ⛷ 🏂 🏋🏻‍♀️ 🤺 🤼‍♀️ 🤸🏻‍♀️ ⛹🏻‍♀️ 🤾🏻‍♀️ 🏌🏻‍♀️ 🏄🏻‍♀️ 🏊🏻‍♀️ 🤽🏻‍♀️ 🚣🏻‍♀️ 🏇🏻 🚴🏻‍♀️ 🚵🏻‍♀️ 🧗🏻‍♀️ 🤹🏻‍♀️” 这时我们怎样才能一次性的输入“做运动女”这个词组才能获得对应的emoji呢？

**Comment by GuoBinyong** [comment]
> 例如，我们输入“微笑”，可以得到emoji“🙂️”。因为“微笑”是一个可以一次性输入的词组。
> 但是“做运动女”这样的词组，对应的emoji有：“ ⛷ 🏂 🏋🏻‍♀️ 🤺 🤼‍♀️ 🤸🏻‍♀️ ⛹🏻‍♀️ 🤾🏻‍♀️ 🏌🏻‍♀️ 🏄🏻‍♀️ 🏊🏻‍♀️ 🤽🏻‍♀️ 🚣🏻‍♀️ 🏇🏻 🚴🏻‍♀️ 🚵🏻‍♀️ 🧗🏻‍♀️ 🤹🏻‍♀️” 这时我们怎样才能一次性的输入“做运动女”这个词组才能获得对应的emoji呢？

有以下方案：
- 方案1：你经常输入 做运动女 来增加它的词频，以便以后可以一次性输入这几个字，然后便可触发 emoji 的联想
- 方案2: 你可以在你的用户词库里增加  做运动女 ，这样也可以一次性输入这几个字，然后便可以触发 emoji 的联想
