### ISSUE TITLE
纠正错码

### ISSUE THREAD

**Issue by youandeanyou** [GuoBinyong/wubixinshiji#4]
梾sgus改成sgoy；俫wgus改成wgoy；慭gusn改成godn；讖ywwy改为ywwg。

**Comment by GuoBinyong** [comment]
你建议的五笔码都是86版的五笔码，新世界版的与86版的不一样
![截屏2022-08-31 17 58 07](https://user-images.githubusercontent.com/19264309/187653223-81fb88dd-cdb3-49d0-84db-a3760c8851cd.png)
![截屏2022-08-31 17 59 06](https://user-images.githubusercontent.com/19264309/187653227-b76897ed-0c07-4f86-9d9a-83983d4f451f.png)
![截屏2022-08-31 17 59 52](https://user-images.githubusercontent.com/19264309/187653236-4c3cd4a4-493c-4826-b311-69003a1a762f.png)

**Comment by GuoBinyong** [comment]
这些不是错码，你反馈是86版五笔的五笔码
